[hotkeys]
record_transcribe = "ctrl + alt + s"
record_quicknote = "ctrl + shift + q"

[recording]
output_format = "wav"
max_duration_seconds = 3600
audio_dir = "~/.hotspeech/audio"

[transcription]
backend = "local"
model = "faster-whisper"
fallback_model = "whisper-1"
language = "en"
api_key = "your-openai-api-key-here"

[storage]
sqlite_path = "~/.hotspeech/hotspeech.db"
keep_last_n = 10

[clipboard]
enabled = true

[webui]
port = 8082
host = "127.0.0.1"
