[hotkeys]
record_transcribe = "ctrl + shift + r"
record_quicknote = "ctrl + shift + q"

[recording]
output_format = "wav"
max_duration_seconds = 3600      # 1 hour max - effectively unlimited for most uses
audio_dir = "~/.hotspeech/audio"

[transcription]
backend = "api"                      # options: api, local
model = "whisper-1"
fallback_model = "faster-whisper"
language = "en"
api_key = "your-openai-api-key-here" # Replace with your actual OpenAI API key

[storage]
sqlite_path = "~/.hotspeech/hotspeech.db"
keep_last_n = 10

[clipboard]
enabled = true

[webui]
port = 8081
host = "127.0.0.1"
